name: Build iOS IPA
on: [push]

jobs:
  build-ipa:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Build IPA from Xcode project
      run: |
        # Navigate to xcode project
        cd xcode-project
        
        # Build the IPA file
        xcodebuild -project dagi.xcodeproj \
          -scheme dagi \
          -configuration Release \
          -destination 'generic/platform=iOS' \
          -archivePath build/dagi.xcarchive \
          archive
        
        # Export IPA
        xcodebuild -exportArchive \
          -archivePath build/dagi.xcarchive \
          -exportOptionsPlist ExportOptions.plist \
          -exportPath build \
          -allowProvisioningUpdates
        
    - name: Upload IPA file
      uses: actions/upload-artifact@v3
      with:
        name: ios-ipa
        path: xcode-project/build/*.ipa
