name: Build iOS
on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build iOS project
      run: |
        # Install Godot (adjust version as needed)
        wget https://github.com/godotengine/godot/releases/download/4.2-stable/Godot_v4.2-stable_macos.universal.zip
        unzip Godot_v4.2-stable_macos.universal.zip
        # Export your project
        ./Godot.app/Contents/MacOS/Godot --headless --export-release iOS
    - name: Upload IPA
      uses: actions/upload-artifact@v2
      with:
        name: iOS-build
        path: build/ios/*.ipa